title: "Suraj's Cybersecurity Projects Blog"
description: "Real-world threat detection using Splunk + MITRE"
remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "air"
plugins:
  - jekyll-feed
