title: "Suraj's Cybersecurity Projects Blog"
email: surajchoudhary3009@gmail.com
description: >-
  A hands-on defensive security blog using Splunk, MITRE ATT&CK, and real-world EDR detections.
baseurl: "/suraj-cyber-blog"  # <- IMPORTANT: Your repo name
url: "https://surajcybersecurityprojects.github.io"

remote_theme: "mmistakes/minimal-mistakes@4.27.2"
minimal_mistakes_skin: "dark"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

permalink: /:categories/:title/

# Author (shows in sidebar)
author:
  name: "Suraj"
  avatar: "/assets/images/profile-pic.png"
  bio: "Cybersecurity Professional | EDR | SOC | Splunk | MITRE ATT&CK"
  location: "India"
  links:
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/suraj-k-3bb9a0190"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/SurajCyberSecurityProjects"

# Navigation (optional)
navigation:
  - title: "Home"
    url: "/"
  - title: "Projects"
    url: /projects/
  - title: "About"
    url: /about/

include:
  - _pages

markdown: kramdown
highlighter: rouge

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true

# Optional: Google Analytics
analytics:
  provider: "google-gtag"
  google:
    tracking_id: ""
    anonymize_ip: false


